# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import userena.models
import django_extensions.db.fields
import django.contrib.auth.models
import easy_thumbnails.fields
import django.utils.timezone
from django.conf import settings
import django.core.validators
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0006_require_contenttypes_0002'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(null=True, verbose_name='last login', blank=True)),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=30, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.', 'invalid')], help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', unique=True, verbose_name='username')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name', blank=True)),
                ('last_name', models.CharField(max_length=30, verbose_name='last name', blank=True)),
                ('email', models.EmailField(max_length=254, verbose_name='email address', blank=True)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('uuid', django_extensions.db.fields.UUIDField(max_length=36, editable=False, blank=True)),
                ('groups', models.ManyToManyField(related_query_name='user', related_name='user_set', to='auth.Group', blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', verbose_name='groups')),
            ],
            options={
                'verbose_name_plural': 'Users',
            },
            managers=[
                (b'objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('user', models.ForeignKey(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BidderCompany',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
            ],
            options={
                'verbose_name_plural': 'Bidder companies',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('registration_number', models.CharField(max_length=255, null=True, db_index=True)),
                ('identification_number', models.CharField(max_length=255, null=True, db_index=True)),
                ('system_id', models.CharField(max_length=40)),
                ('name', models.CharField(max_length=255, null=True)),
                ('full_name', models.CharField(max_length=1024, null=True)),
                ('address', models.CharField(max_length=1024, null=True)),
                ('mail_address', models.CharField(max_length=1024, null=True)),
                ('status', models.CharField(max_length=32, null=True)),
                ('registration_date', models.DateField(null=True)),
                ('location', models.CharField(max_length=255, null=True)),
                ('activity', models.CharField(max_length=1024, null=True, verbose_name='Economic activity')),
                ('economic_activity', models.CharField(max_length=1024, null=True, verbose_name='Company type')),
                ('link', models.URLField(null=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.CreateModel(
            name='CompanyMember',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('company_registration_number', models.CharField(max_length=255, db_index=True)),
                ('first_name', models.CharField(max_length=255, null=True)),
                ('last_name', models.CharField(max_length=255, null=True)),
                ('link', models.URLField(null=True)),
                ('company', models.ForeignKey(to='core.Company', null=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Company members',
            },
        ),
        migrations.CreateModel(
            name='CompanyMemberTitle',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('company_registration_number', models.CharField(max_length=255, db_index=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('company_share', models.CharField(max_length=30, null=True)),
                ('company_member', models.ForeignKey(to='core.CompanyMember', null=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Company member titles',
            },
        ),
        migrations.CreateModel(
            name='ConflictInterest',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('company', models.ForeignKey(to='core.Company')),
            ],
            options={
                'verbose_name': 'Conflict of Interest',
                'verbose_name_plural': 'Conflicts of interest',
            },
        ),
        migrations.CreateModel(
            name='ConflictInterestFamilyMember',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('company', models.ForeignKey(to='core.Company')),
            ],
            options={
                'verbose_name': 'Conflict of Interest (Family Members)',
                'verbose_name_plural': 'Conflicts of interest (Family Members)',
            },
        ),
        migrations.CreateModel(
            name='ContractingAuthority',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('procurement_system_id', models.CharField(help_text=b'Internal ID in the database where the data is scraped from', max_length=40, null=True)),
                ('procurement_number', models.CharField(max_length=255)),
                ('identification_number', models.CharField(max_length=40, db_index=True)),
                ('name', models.CharField(max_length=255)),
                ('town', models.CharField(max_length=255, null=True)),
                ('email', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('webpage', models.URLField(null=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Contracting Authorities',
            },
        ),
        migrations.CreateModel(
            name='ContributorCompanyProcurement',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('company', models.ForeignKey(to='core.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContributorIndividualProcurement',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('company', models.ForeignKey(to='core.Company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('source', models.CharField(max_length=512, verbose_name='Source')),
                ('description', models.TextField(null=True, verbose_name='Description', blank=True)),
                ('notes', models.TextField(null=True, verbose_name='Notes', blank=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Datasets',
            },
        ),
        migrations.CreateModel(
            name='ElectionsContributionCompany',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('company', models.ForeignKey(to='core.Company')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Elections Contribution Companies',
            },
        ),
        migrations.CreateModel(
            name='ElectionsContributionCompanyMember',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('company', models.ForeignKey(blank=True, to='core.Company', null=True)),
                ('company_member', models.ForeignKey(to='core.CompanyMember')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Elections Contribution Company Members',
            },
        ),
        migrations.CreateModel(
            name='ElectionsContributions',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('date', models.DateField(null=True, blank=True)),
                ('election_type', models.CharField(max_length=255, null=True, blank=True)),
                ('election_place', models.CharField(max_length=40, null=True, blank=True)),
                ('political_party', models.CharField(max_length=1024, null=True, blank=True)),
                ('candidate', models.CharField(db_index=True, max_length=255, null=True, blank=True)),
                ('contributor_type', models.CharField(max_length=255, null=True, blank=True)),
                ('contributor_name', models.CharField(db_index=True, max_length=255, null=True, blank=True)),
                ('contributor_address', models.CharField(max_length=255, null=True, blank=True)),
                ('amount', models.DecimalField(null=True, max_digits=10, decimal_places=2, blank=True)),
                ('csv_file', models.FileField(null=True, upload_to=b'/home/azz/projects/veritza/veritza/media', blank=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Elections contributions',
            },
        ),
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=40, choices=[(b'1', b'Spouse'), (b'3', b'Son'), (b'2', b'Daughter')])),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Family members',
            },
        ),
        migrations.CreateModel(
            name='FamilyMemberCompany',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('company', models.ForeignKey(to='core.Company')),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
                ('member', models.ForeignKey(to='core.FamilyMember')),
            ],
            options={
                'verbose_name_plural': 'Family member companies',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('national_id', models.CharField(max_length=40, null=True, verbose_name='National ID', blank=True)),
                ('national_id_type', models.CharField(max_length=40, null=True, verbose_name='National ID Type', blank=True)),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('middle_names', models.CharField(max_length=1024, null=True, verbose_name='Middle Names', blank=True)),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('birth_date', models.DateTimeField(null=True, verbose_name='Birth Date', blank=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Persons',
            },
        ),
        migrations.CreateModel(
            name='ProcurementCompany',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('procurement_system_id', models.CharField(help_text=b'Internal ID in the database where the data is scraped from', max_length=40, null=True)),
                ('procurement_number', models.CharField(max_length=255, db_index=True)),
                ('identification_number', models.CharField(max_length=255, db_index=True)),
                ('name', models.CharField(max_length=1024)),
                ('town', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('postal_address', models.CharField(max_length=1024, null=True)),
                ('webpage', models.CharField(max_length=255, null=True)),
                ('contact_point', models.CharField(max_length=255, null=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Procurement Companies',
            },
        ),
        migrations.CreateModel(
            name='ProcurementCompanyRaw',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('procurement_system_id', models.CharField(help_text=b'Internal ID in the database where the data is scraped from', max_length=40, null=True)),
                ('procurement_number', models.CharField(help_text=b'Procurement official number (ID). Not certain that it is unique!', max_length=255, db_index=True)),
                ('identification_number', models.CharField(help_text=b'ID number of the company which was awarded the procurement', max_length=255, db_index=True)),
                ('name', models.CharField(max_length=1024)),
                ('town', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=255, null=True)),
                ('postal_address', models.CharField(max_length=1024, null=True)),
                ('webpage', models.CharField(max_length=255, null=True)),
                ('contact_point', models.CharField(max_length=255, null=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Procurement Companies (Raw)',
            },
        ),
        migrations.CreateModel(
            name='PublicOfficial',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('system_id', models.CharField(max_length=255, unique=True, null=True, db_index=True)),
                ('name', models.CharField(max_length=255, null=True, db_index=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Public officials',
            },
        ),
        migrations.CreateModel(
            name='PublicOfficialCompany',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('company', models.ForeignKey(to='core.Company')),
                ('official', models.ForeignKey(to='core.PublicOfficial')),
            ],
            options={
                'verbose_name': "Public official's company",
                'verbose_name_plural': 'Public officials companies',
            },
        ),
        migrations.CreateModel(
            name='PublicOfficialReport',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('system_id', models.CharField(max_length=255, db_index=True)),
                ('name', models.CharField(max_length=255, null=True, db_index=True)),
                ('report_name', models.CharField(help_text='Naziv izvje\u0161taja', max_length=255, null=True)),
                ('report_type', models.CharField(max_length=255, null=True)),
                ('year', models.CharField(help_text='Godina', max_length=10, null=True)),
                ('rbr', models.CharField(help_text='Rbr', max_length=10, null=True)),
                ('link', models.URLField(help_text='Link', null=True)),
                ('public_office', models.CharField(help_text='Javna funkcija', max_length=255, null=True)),
                ('public_office_other', models.CharField(help_text='Druga javna funkcija', max_length=255, null=True)),
                ('official_type', models.CharField(help_text='Vrsta funkcionera', max_length=255, null=True)),
                ('address', models.CharField(help_text='Adresa', max_length=255, null=True)),
                ('job', models.CharField(help_text='Stalni radni odnos', max_length=255, null=True)),
                ('company_board_member', models.CharField(help_text='\u010clan organa privrednog dru\u0161tva', max_length=1024, null=True)),
                ('salary', models.CharField(help_text='Mjese\u010dna nadoknada', max_length=255, null=True)),
                ('other_activities', models.CharField(help_text='Obavljanje drugih djelatnosti', max_length=1024, null=True)),
                ('other_activities_salary', models.CharField(help_text='Mjese\u010dna nadoknada', max_length=1024, null=True)),
                ('real_estate', models.CharField(help_text='Nepokretna imovina', max_length=1024, null=True)),
                ('movables', models.CharField(help_text='Pokretna imovina', max_length=1024, null=True)),
                ('movables_others', models.CharField(help_text='Ostala pokretna imovina', max_length=1024, null=True)),
                ('companies', models.CharField(help_text='Vlasni\u0161tvo u privrednim dru\u0161tvima', max_length=1024, null=True)),
                ('company_salary', models.CharField(help_text='Mjese\u010dna plata', max_length=255, null=True)),
                ('annual_income', models.CharField(help_text='Godi\u0161nji prihod od poljoprivrede i dr. djelatnosti', max_length=255, null=True)),
                ('other_income', models.CharField(help_text='Ostali prihodi', max_length=255, null=True)),
                ('credits_debts', models.CharField(help_text='Krediti, dugovi i potra\u017eivanja', max_length=255, null=True)),
                ('spouse', models.CharField(help_text='Ime bra\u010dnog/vanbra\u010dnog druga', max_length=255, null=True)),
                ('spouse_job', models.CharField(help_text='Stalni radni odnos', max_length=255, null=True)),
                ('spouse_other_activities', models.CharField(help_text='Obavljanje drugih djelatnosti', max_length=1024, null=True)),
                ('spouse_movables', models.CharField(help_text='Pokretna imovina', max_length=255, null=True)),
                ('spouse_movables_others', models.CharField(help_text='Ostala pokretna imovina', max_length=1024, null=True)),
                ('spouse_real_estate', models.CharField(help_text='Nepokretna imovina', max_length=255, null=True)),
                ('spouse_companies', models.CharField(help_text='Vlasni\u0161tvo u privrednim dru\u0161tvima', max_length=255, null=True)),
                ('spouse_company_salary', models.CharField(help_text='Mjese\u010dna plata', max_length=255, null=True)),
                ('spouse_annual_income', models.CharField(help_text='Godi\u0161nji prihod od poljoprivrede i dr. djelatnosti', max_length=255, null=True)),
                ('spouse_other_income', models.CharField(help_text='Ostali prihodi', max_length=255, null=True)),
                ('spouse_credits_debts', models.CharField(help_text='Krediti, dugovi i potra\u017eivanja', max_length=255, null=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
                ('official', models.ForeignKey(to='core.PublicOfficial', null=True)),
            ],
            options={
                'verbose_name_plural': 'Public official reports',
            },
        ),
        migrations.CreateModel(
            name='PublicProcurement',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('number', models.CharField(max_length=40, null=True)),
                ('system_id', models.CharField(help_text=b'Internal ID in the database where the data is scraped from', max_length=40, null=True)),
                ('title', models.CharField(max_length=255, null=True)),
                ('subject', models.CharField(max_length=255, null=True)),
                ('value', models.DecimalField(null=True, max_digits=10, decimal_places=2)),
                ('location', models.CharField(max_length=50, null=True)),
                ('description', models.TextField(null=True)),
                ('record_type', models.CharField(max_length=255, null=True, verbose_name='Notice type')),
                ('creation_date', models.DateTimeField(null=True, verbose_name='Creation Date', blank=True)),
                ('link', models.URLField(null=True, blank=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
            ],
            options={
                'verbose_name_plural': 'Public procurements',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('mugshot', easy_thumbnails.fields.ThumbnailerImageField(help_text='A personal image displayed in your profile.', upload_to=userena.models.upload_to_mugshot, verbose_name='mugshot', blank=True)),
                ('privacy', models.CharField(default=b'registered', help_text='Designates who can view your profile.', max_length=15, verbose_name='privacy', choices=[(b'open', 'Open'), (b'registered', 'Registered'), (b'closed', 'Closed')])),
                ('user', models.OneToOneField(related_name='profile', verbose_name='User', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User profiles',
            },
        ),
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('name', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Veritza',
            fields=[
                ('id', models.AutoField(verbose_name='ID', serialize=False, auto_created=True, primary_key=True)),
                ('uuid', django_extensions.db.fields.UUIDField(verbose_name=uuid.uuid4, max_length=36, editable=False, blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created Timestamp')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Last Modified')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_ok', models.NullBooleanField()),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(null=True, verbose_name='Description', blank=True)),
                ('notes', models.TextField(null=True, verbose_name='Notes', blank=True)),
                ('created_by', models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True)),
                ('sources', models.ManyToManyField(to='core.Dataset')),
            ],
            options={
                'verbose_name_plural': 'Veritzas',
            },
        ),
        migrations.AddField(
            model_name='familymember',
            name='public_official',
            field=models.ForeignKey(to='core.PublicOfficial'),
        ),
        migrations.AddField(
            model_name='electionscontributioncompanymember',
            name='election_contribution',
            field=models.ForeignKey(to='core.ElectionsContributions'),
        ),
        migrations.AddField(
            model_name='electionscontributioncompany',
            name='election_contribution',
            field=models.ForeignKey(to='core.ElectionsContributions'),
        ),
        migrations.AddField(
            model_name='dataset',
            name='tags',
            field=models.ManyToManyField(to='core.Tag', blank=True),
        ),
        migrations.AddField(
            model_name='contributorindividualprocurement',
            name='contribution_record',
            field=models.ForeignKey(to='core.ElectionsContributions'),
        ),
        migrations.AddField(
            model_name='contributorindividualprocurement',
            name='created_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='contributorindividualprocurement',
            name='individual',
            field=models.ForeignKey(to='core.CompanyMember'),
        ),
        migrations.AddField(
            model_name='contributorindividualprocurement',
            name='procurement',
            field=models.ForeignKey(to='core.PublicProcurement'),
        ),
        migrations.AddField(
            model_name='contributorcompanyprocurement',
            name='contribution_record',
            field=models.ForeignKey(to='core.ElectionsContributions'),
        ),
        migrations.AddField(
            model_name='contributorcompanyprocurement',
            name='created_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='contributorcompanyprocurement',
            name='procurement',
            field=models.ForeignKey(to='core.PublicProcurement'),
        ),
        migrations.AddField(
            model_name='conflictinterestfamilymember',
            name='member',
            field=models.ForeignKey(to='core.FamilyMember'),
        ),
        migrations.AddField(
            model_name='conflictinterestfamilymember',
            name='public_procurement',
            field=models.ForeignKey(to='core.PublicProcurement'),
        ),
        migrations.AddField(
            model_name='conflictinterest',
            name='official',
            field=models.ForeignKey(to='core.PublicOfficial'),
        ),
        migrations.AddField(
            model_name='conflictinterest',
            name='public_procurement',
            field=models.ForeignKey(to='core.PublicProcurement'),
        ),
        migrations.AddField(
            model_name='biddercompany',
            name='company',
            field=models.ForeignKey(to='core.Company'),
        ),
        migrations.AddField(
            model_name='biddercompany',
            name='created_by',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, null=True),
        ),
        migrations.AddField(
            model_name='biddercompany',
            name='procurement',
            field=models.ForeignKey(to='core.PublicProcurement'),
        ),
        migrations.AddField(
            model_name='alert',
            name='veritza',
            field=models.ForeignKey(blank=True, to='core.Veritza', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptions',
            field=models.ManyToManyField(to='core.Veritza'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(related_query_name='user', related_name='user_set', to='auth.Permission', blank=True, help_text='Specific permissions for this user.', verbose_name='user permissions'),
        ),
    ]
